services:
   intranet:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: home_intranet_v2
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:80"
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "80:80"
    env_file:
      - .env