services:
  db:
    image: postgres:13
    container_name: home-intranet-v2-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  django:
    image: jameslanham/home-intranet-v2-django:latest
    container_name: home-intranet-v2-django
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --no-input --clear &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    image: jameslanham/home-intranet-v2-nginx:latest
    container_name: home-intranet-v2-nginx
    depends_on:
      - django
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - static_volume:/app/staticfiles

volumes:
  static_volume:
  postgres_data: