services:
  django:
    build: 
      context: .
      dockerfile: Dockerfile.Django
    container_name: home-intranet-v2-django
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --no-input --clear &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.Nginx
    container_name: home-intranet-v2-nginx
    depends_on:
      - django
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - static_volume:/app/staticfiles

volumes:
  static_volume: