services:
  django:
    build: 
      context: .
      dockerfile: Dockerfile.Django
    container_name: home-intranet-v2-django
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --no-input --clear &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.Nginx
    container_name: home-intranet-v2-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - django

volumes:
  static_volume:
  