# Generated by Django 5.0.7 on 2024-07-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize_this', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelving_unit',
            name='name',
            field=models.CharField(default='demo', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
