# Generated by Django 5.0.7 on 2024-07-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize_this', '0005_shelf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelf',
            old_name='shelving_unit_id',
            new_name='shelving_unit',
        ),
    ]
