# Generated by Django 5.0.7 on 2024-07-27 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize_this', '0008_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelf',
            old_name='shelving_unit',
            new_name='unit',
        ),
        migrations.AddField(
            model_name='tote',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organize_this.shelving_unit'),
        ),
    ]
