# Generated by Django 5.0.7 on 2024-07-27 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize_this', '0009_rename_shelving_unit_shelf_unit_tote_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tote',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organize_this.shelving_unit'),
        ),
    ]
