# Generated by Django 5.0.7 on 2024-07-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organize_this', '0010_alter_tote_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tote',
            name='unit',
        ),
    ]
